// <auto-generated />
using System;
using ExampleProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ExampleProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210118090956_180120211209")]
    partial class _180120211209
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("uuid-ossp")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ExampleProject.DataAccess.Entities.Report", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReportCreateTime")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ReportType")
                        .HasMethod("hash");

                    b.ToTable("report");
                });

            modelBuilder.Entity("ExampleProject.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password");

                    b.Property<Guid?>("ReportID")
                        .HasColumnType("uuid");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("User")
                        .HasColumnName("user_type");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReportID");

                    b.HasIndex("UserType")
                        .HasMethod("hash");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ExampleProject.DataAccess.Entities.UserInformation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("personal_id");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_information");
                });

            modelBuilder.Entity("ExampleProject.DataAccess.Entities.User", b =>
                {
                    b.HasOne("ExampleProject.DataAccess.Entities.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportID");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ExampleProject.DataAccess.Entities.UserInformation", b =>
                {
                    b.HasOne("ExampleProject.DataAccess.Entities.User", "User")
                        .WithOne("Information")
                        .HasForeignKey("ExampleProject.DataAccess.Entities.UserInformation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExampleProject.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Information");
                });
#pragma warning restore 612, 618
        }
    }
}
